duckbongkim/main

backserver/controllers/controller_admin.js, backserver/models/model_index.js, backserver/models/model_products.js, backserver/routers/router_admin.js, backserver/routers/router_index.js, frontserver/src/components/admin/addAccount.vue, frontserver/src/components/admin/manageUsers.vue, frontserver/src/components/admin/sidebar.vue, frontserver/src/components/layout/FooterLayout.vue, frontserver/src/router/index.js, frontserver/src/views/AdminView.vue
형 상품 명이 너무 짧아서 데이터 넣을 때 문제가 생기더라구요. 상품명 길이를 늘여서 문제 없도록 만들었습니다~~
=> patch products model

backserver/app.js, backserver/routers/router_orders.js, backserver/routers/router_products.js, frontserver/package-lock.json, frontserver/src/components/orders/userWishes.vue, frontserver/src/router/index.js, frontserver/src/views/OrderView.vue, frontserver/src/views/ProductView.vue, 라우터 구조.js
order라우터지옥 탈출... 
장바구니, 찜, 주문 등 페이지 제작중
=> 250102 order라우터지옥 탈출

backserver/app.js, backserver/controllers/admin/controller_account.js, backserver/controllers/auth/controller_login.js, backserver/methods/crypto.js, backserver/middlewares/middleware_checkLogin.js, backserver/models/model_accounts.js, backserver/routers/router_login.js, frontserver/package-lock.json, frontserver/src/components/admin/addAccount.vue, frontserver/src/components/admin/manageOrders.vue, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/router/index.js, frontserver/src/views/ProductView.vue, frontserver/src/views/auth/createAccountView.vue
간단한 오류 수정 커밋이에용
까먹을까봐 먼저 올리고 진행할게요!
=> little patch product라우트 추가,

backserver/models/model_index.js, backserver/models/model_wishes.js, backserver/routers/router_orders.js, frontserver/src/components/orders/userWishes.vue
=> 250102 wish 모델 제작

frontserver/src/router/index.js, frontserver/src/views/auth/loginView.vue
=> add kakao login

backserver/app.js, backserver/controllers/auth/controller_login.js, backserver/controllers/auth/controller_naverLogin.js, backserver/methods/passportSetting.js, backserver/routers/router_login.js, frontserver/src/views/auth/loginView.vue
네이버 로그인 구현. 소셜로그인 할 때 제공되는 이메일을 db에서 확인하고 이메일을 갖는 계정이 없으면 해당 이메일로 account 데이터가 생성되는 것도 구현했습니다.
=> add naver login

backserver/app.js, backserver/controllers/controller_profile.js, backserver/routers/router_profile.js
=> add user profile get request

backserver/models/model_index.js, backserver/models/model_wishes.js, backserver/package-lock.json, backserver/package.json, backserver/routers/router_orders.js, frontserver/package-lock.json, frontserver/package.json, frontserver/src/router/index.js, frontserver/src/views/ProductView.vue
=> 250103 wishes 정의 및 db연동 완

backserver/app.js, backserver/routers/router_list.js, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/components/list/productList.vue, frontserver/src/router/index.js
vue, express 연결 및 동적 router 설정, frontserver에 임시 vue파일 작성 후 데이터 교환 완료
=> 1/3 axios 및 params를 이용한 라우터설정

frontserver/src/components/etc/decanter.vue, frontserver/src/components/etc/glass.vue, frontserver/src/components/etc/holder.vue, frontserver/src/components/etc/ontherocks.vue, frontserver/src/components/etc/opener.vue, frontserver/src/components/etc/straight.vue, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/components/liqueurs/liqueur.vue, frontserver/src/components/liqueurs/traditional.vue, frontserver/src/components/liqueurs/whiskey.vue, frontserver/src/components/liqueurs/wine.vue, frontserver/src/router/index.js, frontserver/src/views/MainView.vue
=> navbar 를 통해 각 페이지로 이동되는 기능 구현

backserver/controllers/admin/controller_ratings.js, backserver/controllers/controller_profile.js, backserver/controllers/post/controller_post.js, backserver/routers/router_profile.js, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/router/index.js, frontserver/src/views/MypageView.vue
=> 동진이형의 사용자 페이지 요청 작업 완료

backserver/routers/router_orders.js, frontserver/src/components/orders/userCart.vue, frontserver/src/components/orders/userWishes.vue, frontserver/src/router/index.js, frontserver/src/views/OrderView.vue, frontserver/src/views/ProductView.vue
01-06 누리 / /  장바구니 READ 완료, DELETE 구현중
=> 250106 장바구니 READ 완료, DELETE 구현중

backserver/routers/router_orders.js, frontserver/src/components/orders/userCart.vue
=> 250106 장바구니 CRD 완료, UPDATE 구현중

frontserver/src/components/orders/userWishes.vue, frontserver/src/views/MypageView.vue, frontserver/src/views/OrderView.vue
=> 마이페이지/오더페이지 디자인

frontserver/public/index.html, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/router/index.js, frontserver/src/views/MainView.vue, frontserver/src/views/testView.vue
=> 우진이 sub 머지 맞춤

frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/views/MainView.vue
=> 우진이 sub 머지

backserver/routers/router_orders.js, frontserver/src/components/orders/makeOrder.vue, frontserver/src/components/orders/userCart.vue, frontserver/src/router/index.js, frontserver/src/views/OrderView.vue, frontserver/src/views/ProductView.vue
ordering products list READ 완성
=> 250108 ordering products list READ 완성

backserver/routers/router_orders.js, frontserver/src/components/orders/userCart.vue, frontserver/src/router/index.js, frontserver/src/views/FinalOrderView.vue, frontserver/src/views/OrderView.vue, frontserver/src/views/ProductView.vue
=> 250108 주문 READ 완, 총액계산 구현중

frontserver/src/components/admin/addOrModifyProduct.vue, frontserver/src/components/admin/manageCoupons.vue, frontserver/src/components/admin/manageOrders.vue, frontserver/src/components/admin/manageProductLocations.vue, frontserver/src/components/admin/manageProducts.vue, frontserver/src/components/admin/manageSupplyFactories.vue, frontserver/src/components/admin/manageUserRatings.vue, frontserver/src/components/admin/manageUsers.vue, frontserver/src/views/auth/createAccountView.vue
어드민 페이지 -> 상품관리 페이지 간단한 검색 필터 추가. 추후에 추가적으로 다른 페이지에 적용.
페이지네이션 간단한 수정.
회원가입 후 로그인 페이지로 이동하도록 변경
=> 정렬 기능은 주말에 할게요 끄어억

backserver/routers/router_orders.js
>>>>> 장바구니 비 로그인시 로그인시 리다이렉트 (완)
=> 250109 찜/장바구니/구매 로그인 확인 및 redir

backserver/controllers/admin/controller_account.js, backserver/routers/router_login.js, frontserver/src/components/admin/manageProducts.vue, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/components/post/boardlist.vue, frontserver/src/views/auth/createAccountView.vue, frontserver/src/views/auth/loginView.vue
=> 어드민 버튼 작업 완료, 유효성 검사 일부 완료

frontserver/package-lock.json, frontserver/package.json, frontserver/src/views/FinalOrderView.vue, frontserver/src/views/ProductView.vue
250109 찜/장바구니/구매 비로그인시 로그인 및 리다이렉트
=> 250109 찜/장바구니/구매 비로그인시 로그인 및 리다이렉트

frontserver/package-lock.json, frontserver/package.json, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/components/layout/basket.vue, frontserver/src/main.js, frontserver/src/plugins/vuetify.js, frontserver/src/router/index.js, frontserver/src/views/MainView.vue
오늘
- carousel을 사용하여 추천배너 다시 만들기, 장바구니 버튼 클릭 시 해당 url로 이동
=> carousel로 추천배너 만들기, 장바구니 클릭시 해당url로 이동하기

backserver/routers/router_orders.js, frontserver/src/components/orders/userCart.vue, frontserver/src/components/orders/userWishes.vue, frontserver/src/views/ProductView.vue
250109 체크박스 구현, 장바구니 선택적 삭제 및 주문
=> 250109 체크박스 구현, 장바구니 선택적 삭제 및 주문

backserver/controllers/admin/controller_product.js, backserver/controllers/post/controller_post.js, frontserver/package-lock.json, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/components/post/boardlist.vue, frontserver/src/components/post/postAll.vue, frontserver/src/components/post/postListAll.vue, frontserver/src/views/FinalOrderView.vue, frontserver/src/views/MypageView.vue, frontserver/src/views/OrderView.vue, frontserver/src/views/PostListView.vue, frontserver/src/views/post/postDetailView.vue
=> 게시물 상세 페이지 어드민은 모든 게시물, 댓글 수정 삭제 가능하도록 수정.

backserver/controllers/admin/controller_order.js, frontserver/package-lock.json, frontserver/package.json, frontserver/src/components/admin/manageOrders.vue, frontserver/src/components/admin/sidebar.vue, frontserver/src/components/layout/HeaderLayout.vue, frontserver/src/views/AdminView.vue, frontserver/src/views/auth/loginView.vue, frontserver/src/views/post/AddOrModifyPostView.vue, frontserver/src/views/post/postDetailView.vue
=> 네브바 상단에 고정.

backserver/routers/router_orders.js, frontserver/src/components/productList/productAll.vue, frontserver/src/views/FinalOrderView.vue, frontserver/src/views/ModifyUserView.vue, frontserver/src/views/auth/createAccountView.vue
=> 결제 완료시 적립금 적용. 적립금 적용버튼 submit 되는 것 수정
